const PRODUCTS = [
  {
    id: 1,
    name: "The Summit Paddle",
    price: 89.99,
    category: "paddles",
    image: "/images/paddle-main.jpg",
    images: ["/images/paddle-main.jpg", "/images/paddle-case.jpg"],
    description:
      "The Summit Paddle is engineered for champions and priced for everyone. Featuring a raw carbon fiber face for elite spin and control, combined with a polymer honeycomb core that delivers explosive power and unmatched feel. USAPA approved and court-ready from day one, the Summit Paddle is your competitive edge whether you're playing recreationally or on the pro circuit.",
    shortDescription: "Raw carbon fiber face • Polymer core • USAPA approved",
    specs: {
      face: "Raw Carbon Fiber",
      core: "Polymer Honeycomb",
      weight: "7.8 – 8.2 oz",
      grip: '4.25" Cushioned Grip',
      length: '16.5"',
      width: '7.5"',
      thickness: "16mm",
      approval: "USAPA Approved",
    },
    stock: 47,
    rating: 4.8,
    reviews: 124,
  },
  {
    id: 2,
    name: "The Base Camp Bundle",
    price: 129.99,
    category: "bundles",
    image: "/images/paddle-main.jpg",
    images: ["/images/paddle-main.jpg", "/images/paddle-case.jpg"],
    description:
      "Everything you need to dominate the court, bundled together and ready for your next peak performance. The Base Camp Bundle includes our flagship Summit Paddle and our premium branded carry case — the perfect starter pack for players who refuse to compromise on quality.",
    shortDescription: "Summit Paddle + Carry Case — the ultimate starter pack",
    specs: {
      includes: "Summit Paddle + Carry Case",
      face: "Raw Carbon Fiber",
      core: "Polymer Honeycomb",
      weight: "7.8 – 8.2 oz",
      grip: '4.25" Cushioned Grip',
      case: "Premium Padded Carry Case",
      approval: "USAPA Approved",
    },
    stock: 23,
    rating: 4.9,
    reviews: 89,
  },
  {
    id: 3,
    name: "The Carry Case",
    price: 39.99,
    category: "accessories",
    image: "/images/paddle-case.jpg",
    images: ["/images/paddle-case.jpg", "/images/paddle-main.jpg"],
    description:
      "Protect your investment with the Paddles Peak premium carry case. Constructed with durable materials and featuring a padded interior, mesh front pocket for balls and accessories, and a smooth zipper closure. Fits all standard pickleball paddles.",
    shortDescription: "Padded interior • Mesh pocket • Fits all paddles",
    specs: {
      material: "Heavy-duty polyester",
      interior: "Padded foam lining",
      closure: "Dual zipper",
      pockets: "1 mesh front pocket",
      strap: "Adjustable shoulder strap",
      fits: "All standard paddles",
    },
    stock: 62,
    rating: 4.7,
    reviews: 56,
  },
];
